In [ ]:
# flask
##import flask # 웹서버 기능 5000번 포트로 서비스

In [2]:
import matplotlib            #시각화 패키지
import numpy as np           #별칭class
print (np.__version__)      #상위 오브젝트가 가진 속성
def pprint(arr):           #엔디 어레이 : 넘파이 의 기본 데이터 배열
    print("type:{}".format(type(arr)))
    print("shape:{}, dimension:{}, dtype:{}".format(arr.shape, arr.ndim, arr.dtype))
    print("Arrays Data:\n", arr)
    #숫자의 디폴트는 int32
arr=[1.0, 2.0, 3.0] #리스트
a=np.array([1,2,3]) #ndarray생성함수 (매개변수: 리스트)
pprint(a)

1.16.5
type:<class 'numpy.ndarray'>
shape:(3,), dimension:1, dtype:int32
Arrays Data:
 [1 2 3]


In [3]:
# 인스턴스상태
a=np.array([0,1,2,3,4,5,6,7,8,9])
print(id(a))    #python core 주소값 확인
print(a.size)    #데이터 개수
print(a.astype(np.float32))    #데이터 타입변경, 넘파이는 행중심, 동질적 데이터
print(a.dtype.itemsize*a.size) #전체 메모리 사이즈 (바이트)
#iterator for in range =>list
a=np.arange(1000)    # => ndarray
a

2251135090976
10
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
40


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [4]:
print(np.zeros((3,4)))  #0
print(np.ones((2,3,4),dtype=np.int16))  #1, 3차원  면, 행, 열
print(np.full((2,2),7))
print(np.eye(4))     #대각행열 identity, 행렬연산에서 항등원
print(np.empty((4,2)))  #쓰레기 값

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[7 7]
 [7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 6.66000491e-321]
 [1.33511969e-306 1.08221785e-312]]


In [6]:
a=np.arange(0,100,10) #ndarray
indices=[1,5,-1]      #list
print(indices)
b=a[indices]          #리스트를 첨자로 사용
print(a)
print(b)

[1, 5, -1]
[ 0 10 20 30 40 50 60 70 80 90]
[10 50 90]


In [11]:
a=np.arange(11,36)  #1차원
print(a)
a.shape=(5,5)   #행열의 갯수가 중요, 정상모양을 갖춰야 한다.
print(a)
print(type(a))
print(a.dtype)
print(a.size)
print(a.shape)  #차수(5,5)
print(a.ndim)    #2차원
print(a.nbytes)   #100바이트 =25*4
print(a.strides)   #(20,4) 다음열의 데이터는 몇바이트를 건너 뛰어야 하는가(5개 일때 건너 뛰었음)
                   #다음 행은 몇바이트를 건너 뛰어야 하는가

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35]
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
<class 'numpy.ndarray'>
int32
25
(5, 5)
2
100
(20, 4)


In [12]:
arr=np.arange(10) #0부터 시작
print(type(arr))
print(arr)
print(arr[5])
print(arr[5:8]) #마지막 불포함
arr[5:8]=12     #데이터 업데이트
print(arr[1:6])

<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 1  2  3  4 12]


In [25]:
#첨자 생략 불가[,4]
arr2d =np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[0])  #행우선 :행
print(arr2d[0][2])
print(arr2d[0,2])
print(arr2d[:2]) #0,1행
print(arr2d[:2, 1:])#끝까지
print(arr2d[:,1:])#모든행
print(arr2d[1,:2])
print(arr2d[2,:1])
arr2d[:2,:1]=0
arr2d[:2,:1]=0
print(arr2d)

[1 2 3]
3
3
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
[[2 3]
 [5 6]
 [8 9]]
[4 5]
[7]
[[0 2 3]
 [0 5 6]
 [7 8 9]]


In [15]:
# 실제 저장은 일렬로 사람이 데이터를 다루는 것은 입체로, 480바이트
#행렬연산에서 앞의 행렬열수와 뒤의 행렬의 행수를 일치 시켜야 행열곱이 가능
#행열곱에서 행렬 앞뒤로 바뀌면 안됨
print("스트라이드의 값", np.ones((3,4,5),dtype=np.float64).strides)
#(160,40,8) #단일 데이터 float64 : 8바이트

스트라이드의 값 (160, 40, 8)


In [20]:

#문제
arr3d=np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]]) # 면2, 행2, 3요소
print("첫면", arr3d[0]) #0번 면
print("첫차원 첫행은=", arr3d[0][0])
print("첫요소는=", arr3d[0][0][0])
#8을 출력하시오
print(arr3d[1][0][1])
#12출력
print(arr3d[1][1][2]) #인덱스

첫면 [[1 2 3]
 [4 5 6]]
첫차원 첫행은= [1 2 3]
첫요소는= 1
8
12


In [21]:
#백업이 안됨: 대입하면 같은 주소를 가리키기 때문에
old_values=arr3d.copy()  #대입: 주소를 복사
arr3d[0]=42       
print("값의 변경후")
print(arr3d)
print("이전값으로 복구")
arr3d=old_values
print(arr3d)

값의 변경후
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
이전값으로 복구
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [23]:
Z=np.arange(36)
print(Z)
Z=Z.reshape((6,6))
reshape2 = Z.reshape((2,3,6))
print(reshape2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]


In [27]:
arr=np.arange(32).reshape((8,4))
print(arr)
print(arr[[1,5,7,2]])            #행중심
print(arr[[-1,-5,-7,-2]])       #거꾸로 인덱싱
print(arr[[1,5,7,2],[0,3,1,2]])

# fancy 인덱싱
print(arr[[1,2,5,7]][:,[0,1,2,3]])
print(arr[[1,5,7,2]][:,[0,3,1,2]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]
[[28 29 30 31]
 [12 13 14 15]
 [ 4  5  6  7]
 [24 25 26 27]]
[ 4 23 29 10]
[[ 4  5  6  7]
 [ 8  9 10 11]
 [20 21 22 23]
 [28 29 30 31]]
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [35]:
arr=[]
for i in range(6):
    ad=[]
    for j in range(6):
        ad.append(i*10+j)
    arr.append(ad)
print(arr)
arr =np.array(arr)
print(arr)
print(arr[[0,2,5]][:,2])       #빨강 print(arr[[0,2,5],2])
print(arr[[3,4,5]][:,[0,2,5]]) #하늘
print(arr[[0,1,2,3,4],[1,2,3,4,5]]) #주황

[[0, 1, 2, 3, 4, 5], [10, 11, 12, 13, 14, 15], [20, 21, 22, 23, 24, 25], [30, 31, 32, 33, 34, 35], [40, 41, 42, 43, 44, 45], [50, 51, 52, 53, 54, 55]]
[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
[ 2 22 52]
[[30 32 35]
 [40 42 45]
 [50 52 55]]


In [41]:
arr=[]
for i in range(6):
    ad=[]
    for j in range(6):
        ad.append(i*10+j)
    arr.append(ad)
print(arr)
arr =np.array(arr)
print(arr)
print(arr[[2,4]][:,[0,2,4]]) #녹색
print(arr[[0,1,2,3,4,5],2])  #빨강
print(arr[[4,5]][:,[4,5]])  #민트
print(arr[0,[3,4]]) #주황

[[0, 1, 2, 3, 4, 5], [10, 11, 12, 13, 14, 15], [20, 21, 22, 23, 24, 25], [30, 31, 32, 33, 34, 35], [40, 41, 42, 43, 44, 45], [50, 51, 52, 53, 54, 55]]
[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
[[20 22 24]
 [40 42 44]]
[ 2 12 22 32 42 52]
[[44 45]
 [54 55]]
[3 4]


In [43]:
#선생님 답
print(arr[:,2]) #빨강
print(arr[0,[3,4]]) #주황
print(arr[[2,4]][:,[0,2,4]])#녹색
print(arr[4:][:,[4,5]]) #민트

[ 2 12 22 32 42 52]
[3 4]
[[20 22 24]
 [40 42 44]]
[[44 45]
 [54 55]]


In [46]:
x= np.array([ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ]) #4*3
#[1,2,3]
#[4,5,6]
#[7,8,9]
#[10,11,12]
v= np.array([1,0,1])
print("타일출력")
vv= np.tile(v,(4,1))
#[[1 0 1]
#[1 0 1]
#[1 0 1]
#[1 0 1]]
print(vv)
# y = x +-*/ vv   #4*3 배열연산 => 요소별 연산
print(y)
# 배열연산 : 양쪽 차원이 일치 해야 함
print(x+v) #4*3, 1*3 broadcasting
x+3

타일출력
[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [49]:
x=np.arange(6).reshape((3,2))
print(x)
#거듭제곱 (행열곱)
#x@x #앞의 행렬 열수와 뒤의 행열의 행수가 일치
#(3*2) (3*2)
#전치행열
x@x.T
print(np.transpose(x))

[[0 1]
 [2 3]
 [4 5]]


array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])

In [54]:
arr=np.arange(24).reshape((2,3,4)) #0,1,2
print(arr)
#print(arr.transpose((1,0,2))) #3x2x4
#print(arr.transpose((0,2,1))) #2x4x3

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [56]:
#Boolena indexing(True/False)
#문자열은 대소문자 구분
names=np.array(['Seoul', 'Daejun','chungju','seoul', 'chungju','Daejun','Daejun'])
data=np.random.randn(7,4)
print(names=='Seoul')     #1,0,0,0,0,0,0
print(data[names=='Seoul',2:]) #0번행
print(data[names== 'Seoul',3]) 
print(names!='Seoul')     #0,1,1,1,1,1,1
print(~(names=='Seoul'))  #0,1,1,1,1,1,1
mask=(names=="Seoul")|(names=='chungju')
print(mask)
print(data[mask])

[ True False False False False False False]
[[ 0.85868612 -1.26080811]]
[-1.26080811]
[False  True  True  True  True  True  True]
[False  True  True  True  True  True  True]
[ True False  True False  True False False]
[[-2.27672584 -0.16639531  0.85868612 -1.26080811]
 [-0.28067297 -0.78529365 -0.14377779  0.43389894]
 [-0.86692866  0.68501011  0.0136162  -0.29595535]]


In [59]:
xarr=np.array([1.1,1.2,1.3,1.4,1.5])
yarr=np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True,False, True,True, False])
print(zip(xarr,yarr,cond))  # 요소별로 데이터를 묶음, zip고유포멧
print(list(zip(xarr,yarr,cond)))
result = [(x if c else y) for x,y,c in zip(xarr,yarr,cond)]# 3항연사자
print("result=",result)

result= np.where(cond,xarr,yarr)
print(result)
#random 난수 정규분포 엣허 출력 16개 출력
arr=np.random.randn(4,4)
print(arr)
print(np.where(arr>0,2,-2))

[(1.1, 2.1, True), (1.2, 2.2, False), (1.3, 2.3, True), (1.4, 2.4, True), (1.5, 2.5, False)]
result= [1.1, 2.2, 1.3, 1.4, 2.5]
[1.1 2.2 1.3 1.4 2.5]
[[ 0.06466536  0.94153375  0.27076567 -1.3651113 ]
 [ 0.72742296 -0.00346682 -0.64265344 -0.10352597]
 [-1.10894602  0.78214137 -0.35281931  0.38090822]
 [ 1.55285953  1.19666883 -2.75729342 -0.19443798]]
[[ 2  2  2 -2]
 [ 2 -2 -2 -2]
 [-2  2 -2  2]
 [ 2  2 -2 -2]]


In [ ]:
# 문제 ) 다음 데이터를 이용하여 두개 참일 때는 0,cond1 참일때는 1,cond2가 참일때는 2 그외 일때는 3으로 처리하여 출력하시오

In [ ]:
result=[]
cond1=np.array([1,0,1,1,0,0,1], dtype=bool)
cond2=np.array([0,1,1,1,0,1,1], dtype=bool)

re=np.where(cond1,cond2)
result=np.where(cond1,0,1)
result=np.where(cond2,2,3)
print(result)

In [64]:
result=[]
cond1=np.array([1,0,1,1,0,0,1], dtype=bool)
cond2=np.array([0,1,1,1,0,1,1], dtype=bool)

for i in range(len(cond1)):
    if(cond1[i] and cond2[i]):
        result.append(0)
    elif cond1[i]:
        result.append(1)
    elif cond2[i]:
        result.append(2)
    else:
        result.append(3)
print("조건문",result)
result=np.where(cond1&cond2,0,np.where(cond1,1,np.where(cond2,2,3)))
print("3항연산자", result)
result =1*(cond1&~cond2)+2*(cond2&~cond1) +3* ~(cond1|cond2)
print("수식을 이용한", result)

조건문 [1, 2, 0, 0, 3, 2, 0]
3항연산자 [1 2 0 0 3 2 0]
수식을 이용한 [1 2 0 0 3 2 0]


In [67]:
x=np.arange(1,10001)
print(x)
y=np.arange(10001,20001)
print(y)
z=np.zeros_like(x) # 다른 행열과 같은 사이즈로 초기화
print(z)
for i in range(10000):
    z[i]=x[i]+y[i]

[    1     2     3 ...  9998  9999 10000]
[10001 10002 10003 ... 19998 19999 20000]
[0 0 0 ... 0 0 0]


In [69]:
a= np.array([1,2,3,4])
b= np.array([5,2,2,4])
print(np.all(a==b))  # 전체가 참일 때 참
print(np.exp(a))     # 하나라도 참이면 참
print(np.exp(a))     #지수함수 (자연대수:2.718)

False
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [70]:
# 선형대수 :선형으로 해결하자. => 비선형도 잘게 나누면 선형

# 행렬의 종류
#-정방행열 : 정사각형(행과 열수가 같은 행열)
#-대칭행열 : 우상단과 좌하단 같은 것
#-대각행열 : scale을 변화시키는 요소
#-단위행열(identity) :행열곱의 항등원, 행열과 역행열을 곱하면 단위행열이 나온다.
#-역행열: 행열의 나눗셈을 위해서 구해서 곱해지는 행열(정방행열만 가능)
#-특이행열: 역행열이 없는 행열
#-직교행열 : 축의 정직교, 각축간의 내적이 0인 행열
#-정방행령이면서 대칭행열: 공분산행열, 상관계수행열, 거리행열
#-공분산 : 두수간의 관계 ((한수-평균)*(다른수-평균))/(n-1)     ##자유도로 나누어줌
#-상관계수(표준화 -1~1 사이 값) : 공분산 / 표준편차의 곱


In [71]:
import numpy as np
F1 = np.array([[1,2],[3,4]]) #2x2
F2 = np.array([[2,2],[2,2]]) #2x2
print(F1)
print(F2)
print(F1+F2)  #요소끼리
print(F1*F2)  #
print(F1@F2)
#행열의 곱은 내적을 구하는 과정이다. 두벡터의 사이각을 구한다.

[[1 2]
 [3 4]]
[[2 2]
 [2 2]]
[[3 4]
 [5 6]]
[[2 4]
 [6 8]]
[[ 6  6]
 [14 14]]


In [ ]:
# 연립방정식의 해
2x + y -2 z =-3
3x     +z   =5
x  +y  -z   =-2

In [72]:
A = np.array([ [2,1,-2],[3,0,1],[1,1,-1] ])
print(A)
b=np.transpose(np.array([[-3,5,-2]]))#열로 전치
print(b)
x= np.linalg.solve(A,b) #A의 역행열을 구해서 b와 곱해줌
print(x)

[[ 2  1 -2]
 [ 3  0  1]
 [ 1  1 -1]]
[[-3]
 [ 5]
 [-2]]
[[ 1.]
 [-1.]
 [ 2.]]


In [74]:
np.dot(np.linalg.inv(A),b)# 내적의 곱

array([[ 1.],
       [-1.],
       [ 2.]])

In [73]:
np.linalg.inv(A)@b #왜 역행열을 구해야 하는가? 행열은 나눗셈이 없어서 역행열 곱해서 사용.

array([[ 1.],
       [-1.],
       [ 2.]])

In [75]:
a=np.array([0,1,0])#y축
b=np.array([1,0,0])#x축
res=np.dot(a,b)#내적 사이각 =직각
print(res)

0


In [76]:
print(np.linalg.norm(a)) # 벡터의 크기
print(np.linalg.norm(b))
print(np.linalg.norm(a)*np.linalg.norm(b))
rad = res/(np.linalg.norm(a)*np.linalg.norm(b))# cos(theta)
print("cos theta",rad)
print(np.arccos(rad)) #theta 갑을 구함
print(np.degrees(np.arccos(rad))) #사람이 알아보는 각도로 표현

1.0
1.0
1.0
cos theta 0.0
1.5707963267948966
90.0


In [77]:
x=np.array([[1,2],[3,4]])
y=np.linalg.inv(x)
print(x)
print(y)
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [ ]:
# 다음 방정식의 해를 구하고 검산하시오
x  +y  +z =6
    2y +5z =-4
2x +5y -z =27

In [78]:
A = np.array([ [1,1,1],[0,-2,1],[2,5,-1] ])
print(A)
b=np.transpose(np.array([[6,-4,27]]))#열로 전치
print(b)
x= np.linalg.solve(A,b) #A의 역행열을 구해서 b와 곱해줌
print(x)

[[ 1  1  1]
 [ 0 -2  1]
 [ 2  5 -1]]
[[ 6]
 [-4]
 [27]]
[[13.]
 [-1.]
 [-6.]]


In [ ]:
# ∴ x=13 y=-1 z=-6
# 검산
# 13+(-1)+(-6)=6

In [82]:
#2번쩨 방법
np.dot(np.linalg.inv(A),b)
#3번째 방법
np.linalg.inv(A)@b

array([[13.],
       [-1.],
       [-6.]])